# Configuracion de la aplicacion
pollaFacil:
  domain: pollafacil
  campeonato: 'Rusia 2018'
# 1: Fase de grupos, 2: Octavos, 3: cuartos, 4: semifinal, 5: tercer lugar, 6: final 
  faseActual: 3
  resultados:
    #resultFile: /DEVELOPER/repositorios/pollafacil/files/resultFile.xlsx
    resultFile: /sdev3/repositorios/pollafacil/files/resultFile.xlsx
    reglasSheet: 'REGLAS'
    primeraFaseSheet: 'PRIMERA FASE'
    octavosFaseSheet: 'OCTAVOS'
    cuartosFaseSheet: 'CUARTOS'
    semiFinalFaseSheet: 'SEMIFINAL'
    tercerPuestoFaseSheet: 'TERCERPUESTO'
    finalFaseSheet: 'FINAL'
    
# Fase de grupo
  faseGrupo:
    #readPath: '/DEVELOPER/repositorios/pollafacil/files/planillas/fase_grupo'
    readPath: '/sdev3/repositorios/pollafacil/files/planillas/primera'
    prefix: 'Pronosticos Primera Fase '
    sheets: 'GRUPO A-GRUPO B-GRUPO C-GRUPO D-GRUPO E-GRUPO F-GRUPO G-GRUPO H'
# Octavos
  octavos:
    #readPath: '/DEVELOPER/repositorios/pollafacil/files/planillas/octavos'
    readPath: '/sdev3/repositorios/pollafacil/files/planillas/octavos'
    prefix: 'Pronosticos_Octavos ' 
    sheet: 'Octavos'
# Cuartos
  cuartos:
    #readPath: '/DEVELOPER/repositorios/pollafacil/files/planillas/cuartos'
    readPath: '/sdev3/repositorios/pollafacil/files/planillas/cuartos'
    prefix: 'Pronosticos_Cuartos_'
    sheet: 'Cuartos'
# Semifinal
  semiFinal:   
    readPath: '/sdev3/repositorios/pollafacil/files/planillas/semiFinal'
    prefix: 'Pronosticos_Semifinales_Rusia_2018_'
    sheet: 'Semis'
# Semifinal
  tercerPuesto:   
    readPath: '/sdev3/repositorios/pollafacil/files/planillas/tercerPuesto'
    prefix: 'Pronosticos_TercerPuesto_Rusia_2018_'
    sheet: 'TercerPuesto'
# Semifinal
  final:   
    readPath: '/sdev3/repositorios/pollafacil/files/planillas/final'
    prefix: 'Pronosticos_Final_Rusia_2018_'
    sheet: 'Final'
    
# Identificacion del servicio 
spring:
  application:
    name: pollafacil
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  session:
    store-type: none
  cloud:
    config:
      enabled: false
    server:
      bootstrap: true

security:
  sessions: NEVER
  basic.enabled: false

server:
  address: 0.0.0.0
  port: 9090
  
# Binding health checks to a different port
management:
  address: 0.0.0.0
  port: 9091
  security.enabled: false

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

# logging
logging:
  config: classpath:logback.xml