# Configuracion de la aplicacion
pollafacil:
  watchPath: /opt/pollafacil/
  readpath: /opt/pollafacil/planillas
  resultFile: /opt/pollafacil/resultFile.xlsx
  commonPrefixPlanilla: 'Pronosticos Primera Fase '
  
# Identificacion del servicio 
spring:
  application:
    name: pollafacil
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  session:
    store-type: none
  cloud:
    config:
      enabled: false
    server:
      bootstrap: true

security:
  sessions: NEVER
  basic.enabled: false

server:
  address: 0.0.0.0
  port: 9090
  
# Binding health checks to a different port
management:
  address: 0.0.0.0
  port: 9091
  security.enabled: false

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

# logging
logging:
  config: classpath:logback.xml