# Configuracion de la aplicacion
pollaFacil:
  domain: pollafacil
# 1: Fase de grupos, 2: Octavos, 3: cuartos, 4: semifinal, 5: tercer lugar, 6: final 
  faseActual: 2
  resultFile: /opt/pollafacil/resultFile.xlsx
  
# Fase de grupo
  faseGrupo:
    readPath: /opt/pollafacil/planillas/fase_grupo
    prefix: 'Pronosticos Primera Fase '
    sheets: 'GRUPO A-GRUPO B-GRUPO C-GRUPO D-GRUPO E-GRUPO F-GRUPO G-GRUPO H'
# Octavos
  octavos:
    readPath: /opt/pollafacil/planillas/octavos
    prefix: 'Pronosticos_Octavos _Rusia_2018_'

# Identificacion del servicio 
spring:
  application:
    name: pollafacil
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  session:
    store-type: none
  cloud:
    config:
      enabled: false
    server:
      bootstrap: true

security:
  sessions: NEVER
  basic.enabled: false

server:
  address: 0.0.0.0
  port: 9090
  
# Binding health checks to a different port
management:
  address: 0.0.0.0
  port: 9091
  security.enabled: false

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

# logging
logging:
  config: classpath:logback.xml