# Configuracion de la aplicacion
pollaFacil:
  domain: pollafacil
  campeonato: 'Rusia 2018'
# 1: Fase de grupos, 2: Octavos, 3: cuartos, 4: semifinal, 5: tercer lugar, 6: final 
  faseActual: 3
  resultados:
    resultFile: /DEVELOPER/repositorios/pollafacil/resultFile.xlsx
    reglasSheet: 'REGLAS'
    primeraFaseSheet: 'PRIMERA FASE'
    octavosFaseSheet: 'OCTAVOS'
    cuartosFaseSheet: 'CUARTOS'
    
# Fase de grupo
  faseGrupo:
    readPath: '/DEVELOPER/repositorios/pollafacil/planillas/fase_grupo'
    prefix: 'Pronosticos Primera Fase '
    sheets: 'GRUPO A-GRUPO B-GRUPO C-GRUPO D-GRUPO E-GRUPO F-GRUPO G-GRUPO H'
# Octavos
  octavos:
    readPath: '/DEVELOPER/repositorios/pollafacil/planillas/octavos'
    prefix: 'Pronosticos_Octavos _Rusia_2018_'
    sheet: 'Octavos'
# Cuartos
  cuartos:
    readPath: '/DEVELOPER/repositorios/pollafacil/planillas/cuartos'
    prefix: 'Pronosticos_Cuartos_Rusia_2018_'
    sheet: 'Cuartos'

# Identificacion del servicio 
spring:
  application:
    name: pollafacil
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  session:
    store-type: none
  cloud:
    config:
      enabled: false
    server:
      bootstrap: true

security:
  sessions: NEVER
  basic.enabled: false

server:
  address: 0.0.0.0
  port: 9090
  
# Binding health checks to a different port
management:
  address: 0.0.0.0
  port: 9091
  security.enabled: false

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

# logging
logging:
  config: classpath:logback.xml